version: '3.9'
services:
  chrome:
    image: selenium/node-chrome:4.4.0-20220831
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_START_XVFB=false
      - SE_DRAIN_AFTER_SESSION_COUNT=2
    restart: always 
    deploy:
      replicas: 4
    entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'

  selenium-hub:
    image: selenium/hub:4.4.0-20220831
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"